### ISSUE TITLE
In Creating the Authentication microservice

### ISSUE THREAD

**Issue by teacher1387** [PacktPublishing/Spring-5.0-By-Example#10]
Hi
I get a strange error
<oauth>
<error_description>Full authentication is required to access this resource</error_description>
<error>unauthorized</error>
</oauth>
what maybe the root of this error
regards

**Comment by claudiooliveirazup** [comment]
Hey @teacher1387 , usually it means the authentication is activated...it is part of Spring Security framework

In that part is it not expected?
