### ISSUE TITLE
service discovery name issue

### ISSUE THREAD

**Issue by eguider** [PacktPublishing/Spring-5.0-By-Example#3]
I think the name here should be `zipkin` (copy/past issue)
https://github.com/PacktPublishing/Spring-5.0-By-Example/blob/d82593ea3e74768f19f085a37f95c81cc9cd9b1c/Chapter07/zipkin-server/src/main/resources/bootstrap.yaml#L13

**Comment by claudioed** [comment]
Hey, @eguider I've made the fix on master branch. Thank you

**Comment by eguider** [comment]
:+1:
